### ISSUE TITLE
Weather Event Notifications

### ISSUE THREAD

**Issue by maxwellvogel** [CSBSJU-CS330-F22/WeatherApp#88]
As a user, I want to receive notifications about upcoming weather events.

**Tasks**
- [ ] Create user interface to select what weather events the user would like to receive notifications.
- [ ] Create a background task that runs on a set interval, fetching the data from the API for the user last known location.  
- [ ] Create a function to check the fetched hourly forecast for the existence of the user defined notification events that did not previously exist the last time the data was fetched.
- [ ] Create function to push a notification to user in the event a weather event is detected in the previously step.

**Acceptance Criteria**
- User is able to set weather events they would like to receive notifications
- User receives a single notification for each new upcoming weather event
